version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    reviewers:
      - "thepieterdc"
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directory: "/"
    open-pull-requests-limit: 1 # avoid merge conflicts
    reviewers:
      - "thepieterdc"
    schedule:
      interval: weekly
