name: Deploy

on:
  push:
    branches:
      - master

jobs:
  snapshot:
    name: Deploy a snapshot to GitHub Packages.

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache the dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Deploy with Maven
      run: mvn -s settings.xml -Dmaven.test.skip=true -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}